* End to End Encryption is a Right. 

[[https://cyberlaw.stanford.edu/blog/2020/01/earn-it-act-how-ban-end-end-encryption-without-actually-banning-it][The EARN IT act]] is a bill put forth by Congress to mandate a backdoor in any encrypted software. This is terrible for journalists, whistleblowers, activists and those who care for data privacy relying on such software to keep them safe from potentially malevolent domestic and international actors, effectively rendering end-to-end encryption illegal.

A backdoor in end-to-end encrypted software won't just let our government access the information -- it'll open doors to give anyone the potential 

[[https://actionnetwork.org/petitions/dont-let-congress-kill-encryption][Sign a petition to stop this here]].
Contact your state representatives to inform them of your perspective on the issue.

(By the way, welcome to my GitHub. You can learn a bit more about me [[https://jacob.chvatal.com][on my website]] or [[https://github.com/jakechv?tab=repositories][check out some of my work]].)
